!include ..\Makefile.defs

VKPATH=$(VK_SDK_PATH)
VCPATH=..\..\vulcmp
VMAT=..\vulmat.obj

CC=cl -I.. -I$(VCPATH)
LN=link /LIBPATH:"$(LIB)"
RM=del /q

ALL=basic. gauss.
GLSLC=$(VKPATH)\Bin\glslc.exe

run: $(ALL:.=.exe) $(ALL:.=.run)

.exe.run:
	$<

.c.exe:
	$(CC) $< $(VMAT) $(VCPATH)\vulcmp.obj $(VKPATH)\Lib\vulkan-1.lib

clean:
	$(RM) $(ALL:.=.exe) $(ALL:.=.o) 

.SUFFIXES: .run .exe .o .c