#version 450
#include "vulmat_comp.h"

layout (local_size_x=UGR, local_size_y=UGR, local_size_z=1) in;

layout (push_constant) uniform Constants {
   VmtDims p;
};

layout( binding = 0 ) writeonly buffer Values {
   float vals[];
};

void main() {
   uint x = gl_GlobalInvocationID.x;
   if ( p.width <= x ) return;
   uint y = gl_GlobalInvocationID.y;
   if ( p.height <= y ) return;
   uint i = y*p.width+x;
   if ( x == y )
      vals[i] = 1.0;
      else vals[i] = 0.0;
}
