#version 450

layout (local_size_x=16, local_size_y=16, local_size_z=1) in;

layout( binding = 0 ) buffer Data {
   uint width;
   uint height;
   uint data[];
};

layout( binding = 1 ) readonly buffer Base {
   float base[];
};

layout( binding = 2 ) writeonly buffer Result {
   float result[];
};

void main() {
   uint x = gl_GlobalInvocationID.x;
   uint y = gl_GlobalInvocationID.y;
   if ( width <= x || height <= y ) return;
   result[ y*width + x ] = base[ data[y]*width+x ];
} 

