#version 450

layout (local_size_x=16, local_size_y=16, local_size_z=1) in;

layout( binding = 0 ) readonly buffer Dimensions {
   uint w, h;
};

layout( binding = 1 ) readonly buffer Base {
   float base[];
};

layout( binding = 2 ) buffer Result {
   float result[];
};

void main() {
   uint x = gl_GlobalInvocationID.x;
   uint y = gl_GlobalInvocationID.y;
   uint i = y*w+x;
   uint j = x*h+y;
   result[j] = base[i];
}
